create table TECHNOLOGIES (
TECHID  NUMBER NOT NULL PRIMARY KEY, 
TECHNAME VARCHAR2(20) NOT NULL
)
create table COURSES (
COURSEID INT NOT NULL,
TECHID INT NOT NULL,
COURSENAME VARCHAR2(30),
COURSEBATCHES INT,
COURSEDURATION VARCHAR2(20),
PRIMARY KEY (COURSEID),
FOREIGN KEY (TECHID) REFERENCES TECHNOLOGIES(TECHID)
)

CREATE TABLE MODULES(
MODULEID INT NOT NULL,
COURSEID INT NOT NULL,
MODULENAME VARCHAR2(20),
MODULEASSIGNMENT VARCHAR2(20),
MODULEDURATION VARCHAR2(20),
PRIMARY KEY (MODULEID),
FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
)


COMMIT;